### ISSUE TITLE
Broken images and unaligned title text in categories section

### ISSUE THREAD

**Issue by therajtiwari** [kjsce-codecell/Blogs#15]
# Bug report

**What is the current behavior?**

![Screenshot from 2021-10-01 12-52-43](https://user-images.githubusercontent.com/55556417/135582089-bbf53ced-c7c5-451d-89cd-6fa9e54ade6e.png)

- Some background images are broken which need to be fixed.
- The category name is not center-aligned in all the cards.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
- Background-images should be working and text must be aligned.

**Comment by sprakash57** [comment]
May I take this one?

**Comment by nis130** [comment]
@sprakash57 sure go ahead

**Comment by sprakash57** [comment]
Hey @nis130 

So I followed all the steps mentioned in the CONTRIBUTING.md to set up the development environment. But I am facing the below issue -

![image](https://user-images.githubusercontent.com/38065786/135704775-926d834e-639d-40f3-b1e0-7c183b8e9327.png)

Steps I followed -

1. yarn install
2. yarn start

**Comment by nis130** [comment]
Hey @sprakash57 Thanks for reporting, I have my exams this week I will look into it after that. If you find the patch for this feel free to open PR I have created a separate issue here #20

**Comment by neelansh15** [comment]
Hello @sprakash57. The issue (#20) has been resolved in #21. Can you please pull and check if you're interested in continuing with this issue?

**Comment by sprakash57** [comment]
Hey, @neelansh15 raised #22. Please review.
