### ISSUE TITLE
Error in sass compiler

### ISSUE THREAD

**Issue by nis130** [kjsce-codecell/Blogs#20]
Error in SASS syntax, probably arising due to some issues with node-sass version
![image](https://user-images.githubusercontent.com/38065786/135704775-926d834e-639d-40f3-b1e0-7c183b8e9327.png)

Steps followed -

1. yarn install
2. yarn start

_Originally posted by @sprakash57 in https://github.com/kjsce-codecell/Blogs/issues/15#issuecomment-932685684_

**Comment by ashwin003** [comment]
Hello!
Is this one available?

**Comment by nis130** [comment]
@ashwin003 yes go ahead.
